### ISSUE TITLE
Answers?

### ISSUE THREAD

**Issue by falmanna** [mbzuai-oryx/Camel-Bench#1]
Hey, thanks for this impressive work.

I am trying to run the benchmark locally and seems like the dataset doesn't have the correct answer?

**Comment by ahmedheakl** [comment]
Hi @falmanna,
Thanks for reaching out. 

Thanks for reaching out! We left the 'answer' fields empty to prevent unauthorized training on our data. Yet, we can give you the accuracy of your generated answers by your model. To evaluate your model:
1. Use our [evaluation script](https://github.com/mbzuai-oryx/Camel-Bench/blob/main/scripts/eval_qwen.py).
2. Replace the inference code with your model's code.
3. Run the script to generate outputs.
4. Submit the outputs to us, and we'll provide the evaluation results/accuracy.

This ensures the benchmark's integrity while allowing you to assess your model's performance. Let me know if you have any other questions!

**Comment by falmanna** [comment]
Thanks @ahmedheakl 

 I actually switched the implementation to litellm lib and was trying with few VLMs locally.
I will reachout over LinkedIn for a more detailed inquiry. 

Best.

**Comment by AhmedMasryKU** [comment]
Hi @ahmedheakl, 

Great work! Is there any validation set that you can publicly release along with the answers? We wanna test a few models and I don't wanna keep spamming your email with many results.

**Comment by ahmedheakl** [comment]
Hi @AhmedMasryKU,
We are not releasing any validation set soon. Please send the results via email, and we will share each category accuracy back.
